language: android
sudo: required
jdk: oraclejdk8

env:
  - ANDROID_EMULATOR_API_LEVEL=24

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25+, latest, cannot get more granular control than this
    # See https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943 for more
    # details.
    - platform-tools #latest
    - build-tools-26.0.1
    - android-26
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-$ANDROID_EMULATOR_API_LEVEL
  licenses:
    - 'android-sdk-license-.+'


before_script:
  - echo y | android update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | android update sdk --no-ui --all --filter build-tools-25.0.2
  - echo y | android update sdk --no-ui --all --filter "sys-img-armeabi-v7a-android-$ANDROID_EMULATOR_API_LEVEL"
  - echo no | android create avd --force -n test -t "android-$ANDROID_EMULATOR_API_LEVEL" --abi armeabi-v7a
  - emulator -avd test -no-skin -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"