language: android
jdk: oraclejdk8

env:
  - ANDROID_EMULATOR_API_LEVEL=19

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25+, latest, cannot get more granular control than this
    # See https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943 for more
    # details.
    - platform-tools #latest
    - build-tools-26.0.1
    - android-26
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-26
  licenses:
    - 'android-sdk-license-.+'

before_install:
 - chmod +x gradlew

script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"